<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>qwz</string>
   </array>
  <key>name</key>
  <string>qwertz</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.qwertz</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(if|dacă|falls|если|else|altfel|sonst|иначе|while|câtTimp|während|пока|for|pentru|für|для|do|execută|tue|делай|break|oprește|brechen|стопэ|continue|continuă|fortsetzen|продолжить|return|returnează|zurückgeben|вернуть|fun|print|afișează|drücke|печать)</string>
          <key>name</key>
          <string>keyword.qwertz</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(sin|cos)</string>
          <key>name</key>
          <string>meta.function-call.qwertz</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([0-9]\d*(?:\.\d+)?)</string>
          <key>name</key>
          <string>constant.numeric.qwertz</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((&amp;&amp;)|(!=)|(==)|(\|\|)|(&gt;)|(&lt;)|(&lt;=)|(&gt;=))</string>
          <key>name</key>
          <string>keyword.operator.qwertz</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.qwertz</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.qwertz</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.qwertz</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.qwertz</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.qwertz</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.qwertz</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comments</string>
        </dict>
       </array>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.qwertz</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.documentation.qwertz</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.block.documentation.qwertz</string>
          <key>end</key>
          <string>(.*?\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.documentation.qwertz</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>comments__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\\&quot;)|(\\n)|(\\t)|(\\r)|(\\0)</string>
          <key>name</key>
          <string>constant.character.escape.qwertz</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{0022}\x{005c}])</string>
          <key>name</key>
          <string>string.qwertz</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
